### ISSUE TITLE
启动后端时候报错 “ERROR 1796 nodejs.AppWorkerDiedError ”| 项目安装问题

### ISSUE THREAD

**Issue by Orca-web** [zhoushaw/Instagram#7]
> 在/service文件下
> npm install
> npm run dev

zhoushaw：你好！你的项目很棒，我很喜欢它。

我在运行你的项目时候，遇到一些麻烦。

我已经顺利完成前面所有安装，包括成功执行`npm install`安装完后端的依赖包

现在卡在 执行`npm run dev`启动后端，下面是报错截图和报错日志。您可以给我一些建议嘛？

![image](https://user-images.githubusercontent.com/59247295/90308648-bad33d00-df13-11ea-8673-d1d89c6eadf5.png)

![image](https://user-images.githubusercontent.com/59247295/90308128-5e6e1e80-df0f-11ea-961f-76e2197b3ba3.png)

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.6
3 info using node@v10.22.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle service@1.0.0~predev: service@1.0.0
6 info lifecycle service@1.0.0~dev: service@1.0.0
7 verbose lifecycle service@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle service@1.0.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/www/Instagram/service/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle service@1.0.0~dev: CWD: /www/Instagram/service
10 silly lifecycle service@1.0.0~dev: Args: [ '-c', 'egg-bin dev -r egg-ts-helper/register' ]
11 silly lifecycle service@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle service@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: service@1.0.0 dev: `egg-bin dev -r egg-ts-helper/register`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid service@1.0.0
15 verbose cwd /www/Instagram/service
16 verbose Linux 3.10.0-1127.18.2.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v10.22.0
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error service@1.0.0 dev: `egg-bin dev -r egg-ts-helper/register`
22 error Exit status 1
23 error Failed at the service@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
提前感谢！

**Comment by Orca-web** [comment]
我找到一个相关参考链，https://github.com/eggjs/egg/issues/3778。

> model 的定义需要这样写
> export default function(app: Application) {
>   const { STRING, INTEGER, DATE } = app.Sequelize;
>   const User = app.model.define('user', {
>       ...
>   });
> 
>   return class extends User {
>      // ...
>   };
> }
> define 返回的类型是 Model 这个类，而这个在 sequelize 的声明中是 abstract class ，不允许直接用，只能继承来用。

但我是门外汉，不知道是否有用？

**Comment by MrGetlman** [comment]
111
